INSERT INTO STORE (ID, CIF_ID, NAME)VALUES (1,'A12345678','CONCEPT_STORE')
INSERT INTO STORE (ID, CIF_ID, NAME)VALUES (2,'A12345678','CONCEPT_STORE')
INSERT INTO STORE (ID, CIF_ID, NAME)VALUES (3,'A12345678','CONCEPT_STORE')

INSERT INTO ADDRESS (ID, STORE_ID, STREET_NAME, NUMBER_OF, POSTAL_CODE, TOWN, PROVINCE) VALUES (1,1,'CALLE DEL OLIVO',1,28400,'VILLALBA','MADRID')
INSERT INTO ADDRESS (ID, STORE_ID, STREET_NAME, NUMBER_OF, POSTAL_CODE, TOWN, PROVINCE) VALUES (2,1,'CALLE DEL OLIVAS',2,28400,'VILLALBA','MADRID')
INSERT INTO ADDRESS (ID, STORE_ID, STREET_NAME, NUMBER_OF, POSTAL_CODE, TOWN, PROVINCE) VALUES (3,1,'CALLE DEL OLIVARES',3,28400,'VILLALBA','MADRID')

INSERT INTO BILLING_ACCOUNT(ID, STORE_ID) VALUES (1,1)
INSERT INTO BILLING_ACCOUNT(ID, STORE_ID) VALUES (2,1)
INSERT INTO BILLING_ACCOUNT(ID, STORE_ID) VALUES (3,1)

INSERT INTO PAYMENT_METHOD (ID, BILLING_ACCOUNT_ID, BANK_ACCOUNT) VALUES (1,1,1234123412341234)
INSERT INTO PAYMENT_METHOD (ID, BILLING_ACCOUNT_ID, BANK_ACCOUNT) VALUES (2,1,1235123512351235)