INSERT INTO STORE (ID, CIF_ID, NAME)VALUES (1,'A12345678','CONCEPT_STORE');
INSERT INTO STORE (ID, CIF_ID, NAME)VALUES (2,'A12345678','CONCEPT_STORE');
INSERT INTO STORE (ID, CIF_ID, NAME)VALUES (3,'A12345678','CONCEPT_STORE');

INSERT INTO ADDRESS (ID, STORE_ID, STREET_NAME, NUMBER_OF, POSTAL_CODE, TOWN, PROVINCE) VALUES (1,1,'CALLE DEL OLIVO',1,28400,'VILLALBA','MADRID');
INSERT INTO ADDRESS (ID, STORE_ID, STREET_NAME, NUMBER_OF, POSTAL_CODE, TOWN, PROVINCE) VALUES (2,1,'CALLE DEL OLIVAS',2,28400,'VILLALBA','MADRID');
INSERT INTO ADDRESS (ID, STORE_ID, STREET_NAME, NUMBER_OF, POSTAL_CODE, TOWN, PROVINCE) VALUES (3,1,'CALLE DEL OLIVARES',3,28400,'VILLALBA','MADRID');

INSERT INTO BILLING_ACCOUNT(ID, STORE_ID) VALUES (1,1);
INSERT INTO BILLING_ACCOUNT(ID, STORE_ID) VALUES (2,1);
INSERT INTO BILLING_ACCOUNT(ID, STORE_ID) VALUES (3,1);

INSERT INTO PAYMENT_METHOD (ID, BILLING_ACCOUNT_ID, BANK_ACCOUNT) VALUES (1,1,1234123412341234);
INSERT INTO PAYMENT_METHOD (ID, BILLING_ACCOUNT_ID, BANK_ACCOUNT) VALUES (2,1,1235123512351235);

INSERT INTO CATALOG (ID, STORE_ID, CATALOG_REF, NAME) VALUES (1, 1, 'COLCHONES_REF','COLCHONES');
INSERT INTO CATALOG (ID, STORE_ID, CATALOG_REF, NAME) VALUES (2, 1, 'ALMOHADA_REF','ALMOHADA');
INSERT INTO CATALOG (ID, STORE_ID, CATALOG_REF, NAME) VALUES (3, 1, 'CANAPE_REF','CANAPE');

INSERT INTO ARTICLE (ID, CATALOG_ID, NAME, BRAND, PICTURE) VALUES (1, 1, 'INFINITY', 'POLIGON', 'http://poligon.es/wp-content/uploads/2018/07/Infinity-1200x457.jpg');
INSERT INTO ARTICLE (ID, CATALOG_ID, NAME, BRAND, PICTURE) VALUES (2, 1, 'NOVA', 'POLIGON', 'https://poligon.es/wp-content/uploads/2017/11/17.nova01.jpg');
INSERT INTO ARTICLE (ID, CATALOG_ID, NAME, BRAND, PICTURE) VALUES (3, 1, 'HYDRA', 'POLIGON', 'http://poligon.es/wp-content/uploads/2018/07/HYDRA-1-1200x457.jpg');
INSERT INTO ARTICLE (ID, CATALOG_ID, NAME, BRAND, PICTURE) VALUES (4, 1, 'VITAL', 'POLIGON', 'http://poligon.es/wp-content/uploads/2018/11/19_VITAL-800x400.jpg');

SELECT C.* FROM CATALOG C
INNER JOIN STORE S ON S.ID = C.STORE_ID
WHERE S.ID = 1